### ISSUE TITLE
Add a dynamically-generated CHANGELOG.md

### ISSUE THREAD

**Issue by ganiulis** [ganiulis/charts#2]
# Summary

- All commit messages are listed.
- Release page also generated.

**Comment by ganiulis** [comment]
See https://keepachangelog.com/en/1.1.0/ for motivation.

**Comment by ganiulis** [comment]
One solution: https://github.com/github-changelog-generator/github-changelog-generator.

**Comment by ginnls** [comment]
Also possible through an Action: https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457.

**Comment by ganiulis** [comment]
Also possible with GitHub Actions: https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457.

**Comment by ganiulis** [comment]
1. Create GitHub Action
2. Checkout
3. Install changelog with `docker run -it --rm -v "$(pwd)":/usr/local/src/your-app githubchangeloggenerator/github-changelog-generator ...`
4. Push updated changelog

See https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/.

**Comment by ganiulis** [comment]
Done. See 1d76d75, 3898589, e5abf6f, and c197c0f.
